# Generated by Django 6.0 on 2026-01-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_slidePost',
            field=models.BooleanField(default=False),
        ),
    ]
