# Generated by Django 6.0 on 2026-01-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_followus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='followus',
            options={'verbose_name_plural': 'FollowUs'},
        ),
        migrations.AddField(
            model_name='followus',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
